blank_issues_enabled: false
contact_links:
  - name: "Documentation technique"
    url: https://github.com/Tatanelprr/cesizen/blob/main/README.md
    about: "Consultez le README avant d'ouvrir un ticket"
